### ISSUE TITLE
Evil datatype lower bound and extent incorrect

### ISSUE THREAD

**Issue by hzhou** [pmodels/yaksa#111]
While working on https://github.com/pmodels/mpich/pull/4758, I find yaksa didn't get following datatype correct:
```
[3] contig (count=3)
[2] resized (lb=6, extent=-9)
[1] contig (count=4)
base: MPI_BYTE
```
The supposed type map: `{ (LB,6),4*(BYTE,0),(UB,-3),(LB,-3),4*(BYTE,-9),(UB,-12),(LB,-12),4*(BYTE,-18),(UB,-21) }`

Error message:
```
##   lb of type = 22; should be -12
##   extent of type = -27; should be 9
##   true_lb of type = 0; should be -18
##   true extent of type = -14; should be 22
## found 4 errors in negextent contig test
```

This is from the test in mpich: `test/mpi/datatype/lbub 1`. It probably is worthwhile to duplicate this test in yaksa so we can test yaksa independently.

Reference: https://github.com/pmodels/mpich/pull/4758#issuecomment-682689861

**Comment by pavanbalaji** [comment]
Is there a test program to reproduce this error?  `test/mpi/datatype/lbub` seems to work fine with `mpich/master`.

**Comment by pavanbalaji** [comment]
Fixed by https://github.com/pmodels/yaksa/pull/130.
