### ISSUE TITLE
Backend pup function for long double

### ISSUE THREAD

**Issue by hzhou** [pmodels/yaksa#112]
The current pup functions assumes the buffer are always aligned (probably true) and displacements are always multiple of the size of basic elements. This is not true for `long double` on 32-bit system. It is size of 12 bytes with 4-byte alignment. When this happens, e. g. `array_of_displs1[j1]  / sizeof(long double)` may be a fraction.

The MPICH test `datatype/sendrecv4.c` is currently broke on 32-bit system because of this.

**Comment by pavanbalaji** [comment]
If the user passes a buffer with the `long double` datatype, it must be correctly aligned for that datatype.  This is true for all datatypes, btw, not just `long double`.  If the user is doing something different (e.g., copying data into a temporary buffer calling a "long double pack/unpack" on that buffer), then that's incorrect usage of Yaksa.

**Comment by hzhou** [comment]
The *correct* alignment for `long double` on 32-bit linux is `4`.
