### ISSUE TITLE
Yaksa is not ubsan clean

### ISSUE THREAD

**Issue by hzhou** [pmodels/yaksa#128]
This is accidentally discovered in https://github.com/pmodels/mpich/pull/4857. Before that PR, mpich configures yaksa before processing ubsan cflags, so the results were clean. The PR move the yaksa configure later and thus inherits the `-fsanitize=undefined` CFLAGS, and ubsan tests start to fail. Reference: https://jenkins-pmrs.cels.anl.gov/job/mpich-review-ch4-ofi/1851/compiler=gnu,jenkins_configure=ubsan,label=centos64_review/testReport/

Synopsis in case the test page expires:
```
not ok  - ./coll/bcast 4
  ---
  Directory: ./coll
  File: bcast
  Num-procs: 4
  Timeout: 180
  Date: "Wed Nov  4 12:41:56 2020"
  ...
## Test output (expected 'No Errors'):
## src/backend/seq/pup/yaksuri_seqi_pup_hvector_int32_t.c:53:38: runtime error: signed integer overflow: 4611686018427387902 * 3 cannot be represented in type 'long int'
## src/backend/seq/pup/yaksuri_seqi_pup_hvector_int32_t.c:29:52: runtime error: signed integer overflow: 4611686018427387902 * 3 cannot be represented in type 'long int'
## src/backend/seq/pup/yaksuri_seqi_pup_contig_hvector_int32_t.c:64:57: runtime error: signed integer overflow: 4611686018427387902 * 3 cannot be represented in type 'long int'
...
```

Suggest: add `ubsan` tests to yaksa review tests -- essentially add `-fsanitize=undefined` to the `CFLAGS`. It is a good idea also run `asan` tests, i.e. `-fsanitize=address`. It needs newer compiler, e.g. `gcc9` for better compiler support.

**Comment by raffenet** [comment]
Most of the failures in Jenkins are the same as above, but there are also a handful of alignment-related issues like this one:
```
not ok  - ./rma/get_struct 2
  ---
  Directory: ./rma
  File: get_struct
  Num-procs: 2
  Timeout: 180
  Date: "Wed Nov  4 13:15:51 2020"
  ...
## Test output (expected 'No Errors'):
## src/frontend/flatten/yaksa_unflatten.c:18:42: runtime error: member access within misaligned address 0x000001a00204 for type 'struct yaksi_type_s', which requires 8 byte alignment
## 0x000001a00204: note: pointer points here
##   00 00 00 00 02 00 00 00  07 00 00 00 01 00 00 00  08 7f 00 00 0c 00 00 00  00 00 00 00 10 00 00 00
##               ^ 
## src/frontend/flatten/yaksa_unflatten.c:19:22: runtime error: member access within misaligned address 0x000001a0029c for type 'struct yaksi_type_s', which requires 8 byte alignment
## 0x000001a0029c: note: pointer points here
##   00 00 00 00 15 00 00 00  00 00 00 00 00 00 00 00  08 00 00 00 08 00 00 00  00 00 00 00 08 00 00 00
##               ^ 
##  No Errors
```

**Comment by pavanbalaji** [comment]
Can we create a ubsan jenkins job for Yaksa, so we don't break it again?

**Comment by pavanbalaji** [comment]
I've created asan/ubsan jobs and verified that Yaksa isn't broken currently.
