### ISSUE TITLE
bash syntax in sh script

### ISSUE THREAD

**Issue by tisaac** [pmodels/yaksa#180]
Hi folks,

https://github.com/pmodels/yaksa/blob/957ff4fc24de2eb87c8892cbd3ec41759c965848/src/backend/cuda/cudalt.sh#L35

The bash substring expansion `${@:2}` is an extension that's not present in all `/bin/sh` implementations.  It caused a `bad substitution` error when I was configuring on a system where `/bin/sh` is dash.

I apologize for not submitting a patch: I didn't try to understand the line that caused the error, I just changed the shebang to `#!/bin/bash` and I thought you wouldn't want to do that for a real fix.

**Comment by raffenet** [comment]
Thanks for the report!
