### ISSUE TITLE
CUDA: automatic SM detection

### ISSUE THREAD

**Issue by pavanbalaji** [pmodels/yaksa#19]
The current yaksa build system requires the user to provide the actual SM required to compile.  This is cumbersome and puts too much burden on the end user.  It'd be cleaner if the build system could automatically detect the SM and use it.

One option would be to use a shotgun approach and build a fat binary with all possible SMs, but that increases the build time significantly.

**Comment by gcongiu** [comment]
What about detecting the attached devices using `lspci` and matching these against some available compute capability map during configure? One problem with this approach is that users will have to compile the code on the compute nodes they wish to run in order for it to work. Maybe the best option is to request the user to run a script that extracts the needed information on the compute nodes and pass the output of such script to the configure?

**Comment by pavanbalaji** [comment]
> What about detecting the attached devices using `lspci` and matching these against some available compute capability map during configure? One problem with this approach is that users will have to compile the code on the compute nodes they wish to run in order for it to work.

Right, that's a significant limitation.  I wouldn't prefer this approach.

> Maybe the best option is to request the user to run a script that extracts the needed information on the compute nodes and pass the output of such script to the configure?

Providing a script to tell the user what SM to use is useful to have, but I was hoping that we could do better than that.  We might need to contact the NVIDIA folks to get an answer on this.

As a side note, our configure can probably be improved somewhat by allowing for a more human-readable format, such as GPU type (e.g., p100).

**Comment by pavanbalaji** [comment]
One possibility to consider is to use something like `nvrtc` to compile the kernel at datatype creation time.  That way, we don't need to know the SM information till runtime.  A side benefit of this approach would be that we won't need to autogenerate all the cases, and instead generate targeted kernels for the exact datatypes that the user creates.

**Comment by pavanbalaji** [comment]
As far as I can tell, folks seem to be recommending building fat binaries for this (e.g., https://forums.developer.nvidia.com/t/auto-detect-gpu-arch-in-make-file/75289).  I guess we could use that as the default, with an option for the user/developer to override it at configure time.
