### ISSUE TITLE
Handle packing and unpacking of basic type fragments

### ISSUE THREAD

**Issue by hzhou** [pmodels/yaksa#206]
It is difficult for the upper layer to always ensure segments contain whole basic types. For example, if the data contains `int + double`, either alignment of `4`, or `8`, or `16` may end up splitting a `double` in half.

Yaksa needs to provide a fallback or slow path for these cases rather than return failures, e.g. returning a lesser `actual_unpack_bytes`.

**Comment by pavanbalaji** [comment]
@hzhou The reason for not doing partial packing of basic types was not for performance, but rather to maintain atomicity, e.g., when the datatype needs to be used for some reduction operation on the remote process.  One could buffer the extra bytes on the remote process when that happens, which could be an alternate solution, but it seemed cleaner to provide a return parameter of `actual_unpack_bytes` for the upper layer to handle, rather than doing partial packs.

**Comment by hzhou** [comment]
> ...but it seemed cleaner to provide a return parameter of `actual_unpack_bytes` for the upper layer to handle, rather than doing partial packs.

That makes sense. Let me think about how to handle it in the upper layer. There are quite a few places in the upper layer, need a way to handle them consistently and in a cleaner way.

**Comment by hzhou** [comment]
In the case of e.g. first segment left a 4-byte fragment of a double, we need yaksa to unpack the next segment with that 4-byte leftover. The upper layer doesn't know how the beginning of the next segment is fragmented since it doesn't have the basic datatype information (or too expensive to retrieve). The upper layer can copy the next segment into a temp buffer along with the leftover, but that is very expensive that we want to avoid. So I am thinking a clean solution need additional yaksa API -- something `yaksa_ipack_with_leftover`. 

A few options:
1. add two more optional arguments to the `yaksa_[I]{pack,unpack}` interface.
2. add additional functions that take leftover fragments
3. add more general `yaksa_[I]{pack,unpack}_iov`

Option 1 is really the simplest, but it makes API more abstruse. If a user just wants to pack/unpack, it is difficult for them to comprehend what all the other parameters are about. I am slightly leaning toward option 2 at the expense of bigger API surface.

**Comment by hzhou** [comment]
Wait, I am missing something. If the upper layer check `actual_pack_bytes`, it should not end up basic_type fragment in the packing stage, then it shouldn't have the issue of unpacking fragments. The whole issue in mpich must be because we failed to check the `actual_pack_bytes` and adjust the segment size accordingly. So the issue might be at MPICH afterall.

**Comment by pavanbalaji** [comment]
> Wait, I am missing something. If the upper layer check `actual_pack_bytes`, it should not end up basic_type fragment in the packing stage, then it shouldn't have the issue of unpacking fragments.

Yes, correct.  The packed data should never have partial basic datatypes.  So the unpack would never have to deal with it.

**Comment by hzhou** [comment]
Reference https://github.com/pmodels/mpich/pull/5715 for fixing the root issue.
