### ISSUE TITLE
backend: optimize yaksuri_seqi_populate_pupfns for compilation

### ISSUE THREAD

**Issue by hzhou** [pmodels/yaksa#21]
Currently, we generate this humongous `yaksuri_seqi_populate_pupfns` function, which is 159800 lines of nested switch cases and compilers are having a very hard time optimizing it. This single file takes many minutes just to compile and become the bottleneck for the development cycle.

Can we do something to speed up the compilation without degrading the performance?

Floating ideas around:
* split it into several smaller functions -- so the compiler stop attempting to juggling all parts together
* calculate hash from yaksi_type_s and use the hash to find the entry

**Comment by hzhou** [comment]
`time make src/backend_seq/pup/yasuri_seqi_pub.lo`:

* -O2: 8 min 25 sec
* -O1: 2 min  7 sec
* -O0: 9 sec

**Comment by yfguo** [comment]
I was building the latest code with `./configure --prefix=$PWD/_inst --with-cuda=/opt/cuda --with-cuda-sm=61` on a 32GB memory machine. The build run out of memory at `CC src/backend/seq/pup/yaksuri_seqi_populate_pupfns.lo`.
