### ISSUE TITLE
cuda: delay resource creation

### ISSUE THREAD

**Issue by raffenet** [pmodels/yaksa#212]
See MPICH issue: https://github.com/pmodels/mpich/issues/5810

I am thinking if we can just replace direct accesses to the global cuda stream array
```
$ git grep yaksuri_cudai_global.stream
hooks/yaksuri_cuda_init_hooks.c:        cerr = cudaStreamDestroy(yaksuri_cudai_global.stream[i]);
hooks/yaksuri_cuda_init_hooks.c:    free(yaksuri_cudai_global.stream);
hooks/yaksuri_cuda_init_hooks.c:    yaksuri_cudai_global.stream = (cudaStream_t *)
hooks/yaksuri_cuda_init_hooks.c:        /* cerr = cudaStreamCreateWithFlags(&yaksuri_cudai_global.stream[i], cudaStreamNonBlocking); */
pup/yaksuri_cudai_event.c:    cerr = cudaEventRecord(event->event, yaksuri_cudai_global.stream[device]);
pup/yaksuri_cudai_event.c:    cerr = cudaEventRecord(event, yaksuri_cudai_global.stream[device1]);
pup/yaksuri_cudai_event.c:    cerr = cudaStreamWaitEvent(yaksuri_cudai_global.stream[device2], event, 0);
pup/yaksuri_cudai_pup.c:                                           &yaksuri_cudai_global.stream[target]);
pup/yaksuri_cudai_pup.c:                                             &yaksuri_cudai_global.stream[target]);
pup/yaksuri_cudai_pup.c:    cerr = cudaStreamSynchronize(yaksuri_cudai_global.stream[target]);
```

 with an inline function like
```
cudaStream_t yaksuri_cudai_get_stream(int device);
```

The CUDA docs state the the default stream is 0 or NULL. Can I calloc the stream array and do this to create the stream when needed?
```c
static inline cudaStream_t yaksuri_cudai_get_stream(int device) {
    if (yaksuri_cudai_global.stream[device] == 0) {
        int cur_device;
        cudaGetDevice(&cur_device);

        cudaSetDevice(device);
        cudaStreamCreateWithFlags(&yaksuri_cudai_global.stream[device], cudaStreamNonBlocking);

        cudaSetDevice(cur_device);
    }
    return yaksuri_cudai_global.stream[device];
}
```

**Comment by raffenet** [comment]
The other part of the CUDA init hook is `cudaDeviceEnablePeerAccess`. Need to understand if this also needs to be delayed to avoid resource creation.

**Comment by Akshay-Venkatesh** [comment]
@raffenet I looked at the code in yaksa and it looks like p2p[i][j] array is set as 0/1 depending on result of cudaDeviceCanAccessPeer call + success status of cudaDeviceEnablePeerAccess. The latter part can be skipped. Older versions of UCX relied on cudaDeviceCanAccessPeer to check peer reachability but we moved to checking reachability by opening memory handles once CUDA started supporting peer access between devices that are masked out by CUDA_VISIBLE_DEVICES. Probably worth moving to explicitly checking if peer is accessible by opening memory handles as cudaDeviceCanAccessPeer is affected by CUDA_VISIBLE_DEVICES.

cc @jirikraus

**Comment by raffenet** [comment]
> @raffenet I looked at the code in yaksa and it looks like p2p[i][j] array is set as 0/1 depending on result of cudaDeviceCanAccessPeer call + success status of cudaDeviceEnablePeerAccess. The latter part can be skipped. Older versions of UCX relied on cudaDeviceCanAccessPeer to check peer reachability but we moved to checking reachability by opening memory handles once CUDA started supporting peer access between devices that are masked out by CUDA_VISIBLE_DEVICES. Probably worth moving to explicitly checking if peer is accessible by opening memory handles as cudaDeviceCanAccessPeer is affected by CUDA_VISIBLE_DEVICES.
> 
> cc @jirikraus

Oops, I didn't see this until just now. Thanks for the info @Akshay-Venkatesh.

**Comment by hzhou** [comment]
> > The other part of the CUDA init hook is `cudaDeviceEnablePeerAccess`. Need to understand if this also needs to be delayed to avoid resource creation.
> 
> #214 is now merged, but it only affects stream creation. Yaksa still calls `cudaDeviceEnablePeerAccess` during init, which might cause some resource allocation on devices. Note: I'm assuming this is the case because there is a complementary API call `cudaDeviceDisablePeerAccess`. @Akshay-Venkatesh suggested we instead determine reachability when opening memory handles, but yaksa doesn't currently utilize memory handles. That would be a significant change, so it would be best to understand the pros and cons before we go that route.

I think we also can delay that to when we actually call `check_p2p_comm`.

**Comment by hzhou** [comment]
I'll push a PR.

**Comment by raffenet** [comment]
This is resolved by #214 and #216.

**Comment by raffenet** [comment]
Actually, I'm going to keep this open until #217 is merged.

**Comment by raffenet** [comment]
#217 is merged so all these issues are resolved.
