### ISSUE TITLE
runtests.py reports no error when test building all failed

### ISSUE THREAD

**Issue by yfguo** [pmodels/yaksa#29]
I tried to run `make test-pack` and the build was failed due to linking error. But the `summary.junit.xml` was still generated with no error.

I think the summary file should not be generated in this case.

**Comment by pavanbalaji** [comment]
I think the summary file should still be generated in this case, but the summary file should list all of the tests as errors.

**Comment by pavanbalaji** [comment]
@yfguo

I just tested this and the `summary.xml` file seems to correctly report that all the tests have failed.  Can you clarify what's the error behavior you are seeing?

**Comment by yfguo** [comment]
Sorry, my description was imprecise.

I was trying this on my own Linux machine. The CUDA had some compatibility issue with the GCC installed, so I was not able to link the test binaries.

After running `make test-pack V=1`, all test failed at linking step with an error similar to this
```==== "make test/pack/pack_cuda_sbuf_dbuf_tbuf" output ====
make[1]: Entering directory '/home/flyxian/mcs/yaksa'
/bin/sh ./libtool  --tag=CC   --mode=link gcc  -O2  -L/opt/cuda/lib64 -L/opt/cuda/lib -o test/pack/pack_cuda_sbuf_dbuf_tbuf test/pack/pack_cuda_sbuf_dbuf_tbuf-pack.o libyaksa.la test/dtpools/libdtpools.la -lcudart -lpthread 
libtool: link: gcc -O2 -o test/pack/.libs/pack_cuda_sbuf_dbuf_tbuf test/pack/pack_cuda_sbuf_dbuf_tbuf-pack.o  -L/opt/cuda/lib64 -L/opt/cuda/lib ./.libs/libyaksa.so test/dtpools/.libs/libdtpools.a -lcudart -lpthread -Wl,-rpath -Wl,/home/flyxian/mcs/yaksa/_inst/lib
/usr/bin/ld: ./.libs/libyaksa.so: undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1328: test/pack/pack_cuda_sbuf_dbuf_tbuf] Error 1
make[1]: Leaving directory '/home/flyxian/mcs/yaksa'
==== make output complete ====
```
Then, looking at the `test/pack/summary.junit.xml`, the content shows
```<testsuites>
  <testsuite failures="0"
             errors="0"
             skipped="0"
             tests="0"
             date="2020-04-13 15:15:45.728198"
             name="summary_junit_xml">
  </testsuite>
</testsuites>
```
It did not say that there is any (build) failure.

**Comment by yfguo** [comment]
I was building the latest code with `./configure --prefix=$PWD/_inst --with-cuda=/opt/cuda --with-cuda-sm=61` on a 32GB memory machine. The build run out of memory at `CC src/backend/seq/pup/yaksuri_seqi_populate_pupfns.lo`.

**Comment by pavanbalaji** [comment]
> I was building the latest code with `./configure --prefix=$PWD/_inst --with-cuda=/opt/cuda --with-cuda-sm=61` on a 32GB memory machine. The build run out of memory at `CC src/backend/seq/pup/yaksuri_seqi_populate_pupfns.lo`.

This is unrelated and should be reported on pmodels/yaksa#21

**Comment by yfguo** [comment]
Tried the latest code, confirmed to have the same problem.
