### ISSUE TITLE
Replace cudaStreamCreate with cudaStreamCreateWithFlags

### ISSUE THREAD

**Issue by gcongiu** [pmodels/yaksa#31]
`cudaStreamCreate` will perform implicit synchronization with the default stream (`stream 0`). In order to have pure asynchronous behavior `cudaStreamCreateWithFlags` should be used with flag `cudaStreamNonBlocking` instead (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__STREAM.html#group__CUDART__STREAM_1gb1e32aff9f59119e4d0a9858991c4ad3).

**Comment by pavanbalaji** [comment]
> `cudaStreamCreate` will perform implicit synchronization with the default stream (`stream 0`). In order to have pure asynchronous behavior `cudaStreamCreateWithFlags` should be used with flag `cudaStreamNonBlocking` instead (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__STREAM.html#group__CUDART__STREAM_1gb1e32aff9f59119e4d0a9858991c4ad3).

Thanks, @gcongiu.  Would you mind creating a PR for this?

**Comment by pavanbalaji** [comment]
This was fixed by #32
