### ISSUE TITLE
Yaksa need to detect if the GCC used and CUDA are compatible at configure time

### ISSUE THREAD

**Issue by shawnccx** [pmodels/yaksa#51]
When using gcc 7.3.1 and cuda support, the below linking failure shows up when doing tests:
```
[caochong@node01 yaksa]$ make testing
==== executing testlist /export/home/caochong/git/yaksa/test/simple/testlist.gen ====
test/simple/simple_test
>>>> return status: FAILURE
>>>> elapsed time: 4.490391 sec
==== "make test/simple/simple_test" failed ====
make[1]: Entering directory '/export/home/caochong/git/yaksa'
  CCLD     test/simple/simple_test
./.libs/libyaksa.so: undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status
```

CUDA version 10.1

This failure is not showing when using gcc 4.8.5

**Comment by pavanbalaji** [comment]
The linker seems to think that it's a C++ object file, probably because of the `nvcc` integration.  I don't have access to a CUDA system with `gcc-7.3.1`.  Let me see if our admins can set it up for me to test it out.

**Comment by yfguo** [comment]
I have renamed the issue because this is due to the compatibility of CUDA installation and GCC. Yaksa should detect this at configure time and throw and error of "incompatible GCC and CUDA version".

Here is the official list from CUDA doc about compatibility.
https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#system-requirements

**Comment by pavanbalaji** [comment]
Yes, the check is too specific to the distributions and kernel versions.  I think it'd be messy to do this in Yaksa.  I think we can ignore this unless it becomes a recurring problem with users that an FAQ page cannot help answer.  Hopefully Google would cache this issue and show it if someone searches for it.
