### ISSUE TITLE
option: allow YAKSA_ENV_MAX_NESTING_LEVEL to be 0

### ISSUE THREAD

**Issue by hzhou** [pmodels/yaksa#9]
Environment variable YAKSA_ENV_MAX_NESTING_LEVEL controls the max nested level during runtime to use the expanded static backend code. Currently, only 1, 2, 3 are allowed. We should allow 0 as well, at which only the built-in types directly use the backend code.

**Comment by pavanbalaji** [comment]
This was fixed in the cleanup done during pmodels/yaksa#39
